[tool.poetry]
name = "blazingml"
version = "2.0.0"
description = "Personal ML library"
license = "MIT"
authors = ["Gianluca Rossi <gr.gianlucarossi@gmail.com>"]
maintainers = ["Gianluca Rossi <gr.gianlucarossi@gmail.com>"]
readme = "README.md"
packages = [{include = "blazingml"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
scipy = "^1.9.1"
loguru = "^0.6.0"
omegaconf = "^2.2.3"
pytorch-lightning = "^1.7.7"
scikit-learn = "^1.1.2"
timm = "^0.6.7"
torchmetrics = "^0.9.3"
tqdm = "^4.64.1"
transformers = "^4.22.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
ipdb = "^0.13.9"
mypy = "^0.971"
isort = "^5.10.1"
black = "^22.8.0"

[tool.poetry.group.medical.dependencies]
pydicom = "^2.3.0"
pylibjpeg = "^1.4.0"
pylibjpeg-libjpeg = "^1.3.1"
pylibjpeg-openjpeg = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
